### ISSUE TITLE
A bit lost after a fresh install - Sorry, something went wrong

### ISSUE THREAD

**Issue by Thireus** [rosenfeld/gitorious-cookbooks#11]
Hi,

I made a fresh install on a fresh new clean debian 6.0 from your sources, everything went fine, but once I try to login on Gitorious webpage, I've got this error:

"Sorry, something went wrong

Gitorious encountered an server error. We are automatically notified of errors and will look into it. If the error persists beyond what's reasonable, let us know."

Login: admin@gitorious.local
Password: password

Login info, from file: gitorious-cookbooks / gitorious / attributes / default.rb

Am I missing something to do after the installation?

Also, can you provide more information relative to Gitorious security and parameters/passwords to change right after the install?

Thanks for your amazing work!

**Comment by rosenfeld** [comment]
If the password were wrong, you would probably receive a message telling you this, not a "Sorry, something went wrong". This means something is wrong with your Gitorious installation. Please take a look at the servers log. Also, make sure you're accessing the site using the same FQDN listed in your configuration.

I'd advise you from now on to get help in the Gitorious mailing list. I can help you but posting there is more likely to get a faster response.

If you had set up a real e-mail, you could ask Gitorious to reset your password if you want to change it or forgot it. There are other ways of changing a user password but we should first take care of the actual problem before trying to change your user password.

And actually, the login info should be taken from your node.json file (downloaded in the README instructions) instead of relying on the defaults.

And thanks! Great that you liked it :)

**Comment by Thireus** [comment]
Thank you for your reply, you are a chef!

The issue was related to FQDN which means, I had to edit the /var/www/gitorious/config/gitorious.yml and put the correct gitorious_host there.

Then, restarted apache, and everything works like a charm :)

Thank you for your reply, I was stupid not to change settings after wget "/root/chef-solo/node.json". Next time I'll be more careful!

**Comment by rosenfeld** [comment]
Don't worry, you were not the first one to skip all README instructions (as if they were big) nor will be the last one ;)
