### ISSUE TITLE
Update to Gitorious 2.1.0

### ISSUE THREAD

**Issue by bilke** [rosenfeld/gitorious-cookbooks#15]
I tried it by specifying another `reference` to the appropriate tag in _node.json_ but it failed. Unfortunately I have experience in chef to fix that by myself.

**Comment by rosenfeld** [comment]
Hi Bilke, this has just been fixed by Ronald on last pull request I've just accepted. Already tested it with 2.1.0.

**Comment by bilke** [comment]
I tried it but got the following error:

```
    ERROR: service[git-daemon] (gitorious::default line 180) has had an error
    ...
    FATAL: Chef::Exceptions::Exec: service[git-daemon] (gitorious::default line 180) had an error: /etc/init.d/git-daemon start returned 1, expected 0
```

When I manually start the daemon with ´/etc/init.d/git-daemon start´ I get the following error:

```
    Starting git-daemon: /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/source.rb:572:in `load_spec_files': https://github.com/roman/rots.git (at master)is not checked out. Please run `bundle install`(Bundler::GitError)
```

According to [this article](http://famousphil.com/blog/2011/06/installing-gitorious-on-centos-5-6-x64) I had to run the following to made it work:

```
    cd /var/www/gitorious
    bundle pack
    bundle install –path vender/cache
```

Then I ran `chef-solo` again.

**Comment by rosenfeld** [comment]
It seems that bundle wasn't completed in your first chef run. This situation is hard to replicate. I can't know why bundle didn't work for you this time. But the actual fix is just to do what the error message said: "Please run `bundle install`", and since install is the default action, just `bundle` should suffice. You don't need to pack nor install it in a different path if you're running it as root.

**Comment by juniovitorino** [comment]
Unfortunatelly i'm experiencing the same problem that @bilke, when i run `chef-solo` the setup raise this error:

> [Thu, 15 Mar 2012 15:04:33 -0300] ERROR: Running exception handlers
> [Thu, 15 Mar 2012 15:04:33 -0300] ERROR: Exception handlers complete
> [Thu, 15 Mar 2012 15:04:33 -0300] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
> [Thu, 15 Mar 2012 15:04:33 -0300] FATAL: Chef::Exceptions::Exec: service[git-daemon](gitorious::default line 180) had an error: Chef::Exceptions::Exec: /usr/sbin/invoke-rc.d git-daemon start returned 1, expected 0

Reading this issue thread i did as @bilke sayed and go to /var/www/gitorious and run, `bundle pack ; bundle install` and tried run chef-solo again. no success.

Trying start it manually i got this message error:

> Starting git-daemon: Invalid gemspec in [/usr/lib/ruby/gems/1.8/specifications/json-1.6.1.gemspec]: invalid date format in  specification: "2011-09-18 00:00:00.000000000Z"

and now i'm lost. =[

**Comment by rosenfeld** [comment]
What Gitorious and Debian/Ubuntu versions are you using so that I could try to replicate the issue?

Also, have you made any other changes to the recipes?

I'll only be able to take a look at this in the weekend most probably though...

**Comment by rosenfeld** [comment]
Also, maybe this is some temporary failure in the RubyGems server. You could try it again later...

**Comment by rosenfeld** [comment]
What is the output of "gem --version"?

**Comment by rosenfeld** [comment]
I have also found this: http://biboyatienza.blogspot.com/2011/11/invalid-gemspec-in-varlibgems18specific.html

**Comment by rosenfeld** [comment]
I guess you're using Ubuntu as I only see this error reported for Ubuntu when searching Google. Have you tried installing it in a Debian box?

**Comment by juniovitorino** [comment]
Wow a lot of things, here i thank you in advance for your availability. Let's go.

Yeah, i'm trying install in a Ubuntu LTS 10.04.4 64Bits box, the weird is that i finish this setup smoothly two days ago. 
I didn't made any changes in recipes, just in node.json file
The gem --version output is 1.4.2 as advised.

I also believes that it could be temporary failure, i will setup a different gems source and back to keep in touch.

**Comment by juniovitorino** [comment]
@rosenfeld i got it up and running marvelously now, the problem was in `bundle install --path vendor/cache` command that i was typing, the correct is like @bilke shown. `bundle install --path vender/cache`

**Comment by rosenfeld** [comment]
It doesn't make any difference where you're installing your gems. The problem was that you probably downloaded a corrupted gem first. It would probably work if you "rm -rf vendor/cache; bundle install --path vendor/cache". You could choose any other directory for bundle installing. I just find it strange that this bug seems to be only reported in Ubuntu. That's one of the reasons I always found Ubuntu to be an unstable system.

It shouldn't be necessary to specify any path to Bundler. It would probably work if you removed your gems from the default path and run "bundle" again too. For some reason sometimes you guys are downloading corrupted gems and RubyGems is not complaining about this. Maybe this is a bug in this old RubyGems but unfortunately you'll have to keep with it until Gitorious is upgraded to a newer Rails version... :(
