### ISSUE TITLE
Exception on fresh debian 6.0.3

### ISSUE THREAD

**Issue by jonwjones** [rosenfeld/gitorious-cookbooks#16]
I'm a complete newb at this stuff so I'm probably doing something stupid. I did a fresh install of debian 6.0.3 and followed the readme but I keep getting an exception when I run 'chef-solo'. Any guidance would be much appreciated.

Here is the log it wrote out:

```
Generated at Tue Jan 17 09:43:00 -0600 2012
Chef::Exceptions::Exec: service[git-daemon] (gitorious::default line 180) had an error: Chef::Exceptions::Exec: /usr/sbin/invoke-rc.d git-daemon start returned 1, expected 0
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/command.rb:127:in `handle_command_failures'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/command.rb:74:in `run_command'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider/service/init.rb:37:in `start_service'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider/service.rb:57:in `action_start'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:45:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:76:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:312:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:160:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/solo.rb:192:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/solo.rb:183:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/solo.rb:183:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application.rb:67:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/chef-solo:25
/usr/bin/chef-solo:19:in `load'
/usr/bin/chef-solo:19
```

**Comment by rosenfeld** [comment]
Please, try run "chef-solo" again to see if the problem reproduces itself... The problem seems to be caused by a failure while trying to run this command as root:

```
invoke-rc.d git-daemon start
```

Try to run it yourself and report the output of this command.

**Comment by jonwjones** [comment]
Same error as before on the 'chef-solo'.

When I run 'invoke-rc.d git-daemon start' I get the following:

```
Starting git-daemon: /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/source.rb:572:in `load_spec_files': https://github.com/roman/rots.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError)
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/source.rb:385:in `local_specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/source.rb:555:in `specs'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:147:in `resolve'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:145:in `each'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:145:in `resolve'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:90:in `specs'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:135:in `specs_for'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/definition.rb:124:in `requested_specs'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/environment.rb:23:in `requested_specs'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:11:in `setup'
from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler.rb:110:in `setup'
from /var/www/gitorious/script/../config/../config/preinitializer.rb:16
from /var/www/gitorious/script/../config/boot.rb:28:in `load'
from /var/www/gitorious/script/../config/boot.rb:28:in `preinitialize'
from /var/www/gitorious/script/../config/boot.rb:10:in `boot!'
from /var/www/gitorious/script/../config/boot.rb:123
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
from /var/www/gitorious/script/../config/environment.rb:11
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
from /var/www/gitorious/script/git-daemon:11
failure

invoke-rc.d: initscript git-daemon, action "start" failed.
```

**Comment by rosenfeld** [comment]
This is interesting... Bundler should have been called as "bundle --without development test" by the recipe. Since Rots is required only for testing Gitorious (the test environment), it shouldn't be depending on Rots... What is the Gitorious git url and branch you're trying to install Gitorious from? I'd like to take a look at how Gemfile is defined there... Anyway, Bundler should have failed in the recipe before it tried to start the daemon...

You can also try running "bundle" directly inside your Gitorious checkout dir, but it shouldn't be required... This is indeed strange... I'll try to reproduce it on a fresh Debian when I get some free time...

**Comment by jonwjones** [comment]
I left it as the default that was in the json:
    git: {
    url: "git://gitorious.org/gitorious/mainline.git",
    reference: "v2.1.0"
    },

**Comment by rosenfeld** [comment]
Indeed, as you can see, Rots is declared under the "test" group and it should be required when "bundle install" was run with "--without test". Have you made any custom process besides running "chef-solo"?

**Comment by rosenfeld** [comment]
Forgot the URL: http://gitorious.org/gitorious/mainline/blobs/029c723fe7b5b624f891ab69fda5f49238bf55fb/Gemfile

**Comment by jonwjones** [comment]
installed Debian on vm
added my user to sudoers list
followed your readme

**Comment by jonwjones** [comment]
I can attempt a previous version of debian, I just figured latest was the best way to go.

**Comment by rosenfeld** [comment]
Humm... I never tried installing it with "sudo". I don't think it should yield to any problems, but I'll give it a try when I find some time... What is your user name?

**Comment by jonwjones** [comment]
The first time I attempted it via root by using 'su' and on the second attempt I did via sudo with username 'jon'

**Comment by rosenfeld** [comment]
Ok, 'jon' shouldn't cause any issues. So I'll try to repeat the instructions in the README and try to replicate your problems when I find some time. It shouldn't give any problems and should be a fully automated install...

For the meanwhile, you could try to run just "sudo bundle" inside /var/www/gitorious. Let me know if you can start the git-daemon this time...

**Comment by jonwjones** [comment]
I ran 'sudo bundle' in /var/www/gitorious then did 'invoke-rc.d git-daemon start'. Strangely it is still hitting an issue with rots and suggesting I 'bundle install'.

I'll keep poking at it till you find time to test it.

**Comment by rosenfeld** [comment]
Try removing /var/www/gitorious/.bundle/config, before running "bundle". It was really run as "--without test development" and those settings were stored in this file.

**Comment by jonwjones** [comment]
Doing the remove, 'bundle install', then 'invoke-rc.d git-daemon start'. Now it says that git-daemon started successfully.

**Comment by rosenfeld** [comment]
And what happens when you run "chef-solo" now?

**Comment by jonwjones** [comment]
Ran without fault.

**Comment by dhm116** [comment]
I had this same issue, but I resolved it temporarily by removing the reference to rots in the Gemfile and re-running bundle

**Comment by rosenfeld** [comment]
Interesting... So, this seems to be reproducible... I'll see if I get some time tonight for downloading a fresh Debian and try the procedures in README...

**Comment by rosenfeld** [comment]
Sorry, couldn't reproduce here. I've tried with a fresh install of Debian 6.0.3 (network install CD) on VirtualBox and followed the instructions in README... Gitorious is running here after "chef-solo"...

**Comment by dhm116** [comment]
For what it's worth, I was also using sudo. I was, however, using Ubuntu 10.04.

**Comment by jonwjones** [comment]
I will close the issue since it can't be reproduced and we did figure out a work around. 

Thanks for your time and all the pointers!

**Comment by rosenfeld** [comment]
Ok, let me know if you have any news about this.

**Comment by altodor** [comment]
I've stumbled over the exact same issue today, and reproduced it on 2 different VPS's. The workaround works but afterwards Gitorious hangs while trying to create a repository. Maybe I should note I'm trying this out on a OpenVZ VPS with the latest Debian 6 templates.

**Comment by rosenfeld** [comment]
Have you ever being able to create a repository on your Gitorious install? Could it be a hang caused by the mailing system? Maybe Gitorious is trying to deliver a message after the repository creation and is timing out for some reason... I wouldn't suspect that much on the Chef installation with regards to this issue...

**Comment by altodor** [comment]
Yep, i tried the script a couple of months back, and it worked. I tried it now without the smtp recipe and I still get the same issue. Anyway, just wanted to note that the rots issue is still persisting.
Edit:
Ok, it seems i figured it out, first the RAILS_ENV variable wasn't set, so I had to execute this command "export RAILS_ENV=production", then poller wasn't running so I had to start it as the git user script/poller start. Afterwards everything ran like normal. I still think it has something to do with the workaround, since it was working quite nicely before the rots issue.

**Comment by rosenfeld** [comment]
If only I could reproduce the issue with ROTS... This is really strange because ROTS shouldn't be needed at all for the production server. I'm sure about this because I was the author of the commit that introduced ROTS for writing the integration test for the OpenID login. But it is only required by the test environment and since "bundle" is run with "--without development test", I don't understand why you guys are experiencing issues with ROTS... This issue has never raised in any of my attempts...

**Comment by rosenfeld** [comment]
By the way, if you're going to try installing Gitorious again, could you please test on latest release (2.1.1) and let me know if it works? It was released today I guess, but I don't have time for testing it today... too much work here...

**Comment by xvonabur** [comment]
Same problem with 2.1.1.

**Comment by rosenfeld** [comment]
It seems lots of people are having this issue. Hopefully, someone who is able to reproduce it can figure out the fix and send me a pull request, or some detailed explanation on why it is not working...

**Comment by daokouer** [comment]
I had this same issue (Ubuntu11.10), resolved it by doing this:

cd /var/www/gitorious/
bundle pack
bundle install --path vendor/cache

ref: http://stackoverflow.com/questions/8055711/gitorious-rots-ruby-on-rails-error

**Comment by rosenfeld** [comment]
But the real issue is that ROTS is only required for the testing environment. There is another issue that we couldn't identify yet that is causing bundle to run without "--without-development --without-test", and that is why it tries to use ROTS.

The proper fix is trying to figure out what piece is trying to do so. I could debug this if I could replicate the issue.

If someone can replicate this issue and doesn't mind in sharing the server via SSH with me, I could try to debug it on my free time (most likely sometime in the weekend).

**Comment by digitalresistor** [comment]
I'm not using chef, but I am seeing this issue on my gitorious install. The work-around of doing bundle install --path vendor/cache works for me as well...

**Comment by rosenfeld** [comment]
As far as I can tell you Christian has removed the ROTS dependency from the Gemfile, so this issue is unlikely to happen in newer Gitorious releases. I don't agree with ROTS removal, but anyway...

And it shouldn't make any difference what path you use in bundle install. I don't even know why it would be necessary to install the gems to a different path than the default one because this only seems to affect Ubuntu boxes and I don't use them. Maybe just trying to remove .bundle/config and run "bundle install" again without any options would probably fix the issue too.

**Comment by rosenfeld** [comment]
Well actually, this issue was first reported on Debian, but I never faced this issue myself to debug it. Maybe I should change the recipe not to run with the "--without" option as it only seems to cause troubles and no benefit...
