### ISSUE TITLE
apache reload files

### ISSUE THREAD

**Issue by jassinm** [rosenfeld/gitorious-cookbooks#18]
hi  on the last apache reload i get https://gist.github.com/1961703 . mod_passenger.so does not exist . only mod_passenger.c is available in folder. seems like it was not build. 
thanks for helping

**Comment by jassinm** [comment]
just read the docs :) 
LoadModule passenger_module /usr/lib/ruby/gems/1.8/gems/passenger-3.0.11/ext/apache2/mod_passenger.so
  1 LoadModule passenger_module /usr/lib/ruby/gems/1.8/gems/passenger-3.0.11/ext/apache2/mod_passenger.so
   PassengerRoot /usr/lib/ruby/gems/1.8/gems/passenger-3.0.11
   PassengerRuby /usr/bin/ruby1.8

**Comment by rosenfeld** [comment]
I've commented this on the Gist instead of here :) Just mirrorring it here too:

That is indeed strange, but this is not a bug on the Gitorious recipe, but in the Apache recipe instead. Did you try more than once and it always happen? I mean, is it reproducible, so that I can take a look at it? If so, I could try to upgrade the "apache" recipe (I'm not its maintainer). Then, let me know what exact Debian/Ubuntu distribution you have tried it on.

If that is not reproducible then sorry but I won't be able to invest time on it as I'm no longer working with Gitorious to put so much effort on this recipe.
