### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by planestraveler** [rosenfeld/gitorious-cookbooks#27]
The git command fetch should ensure that the owner of the repository is the user git and the group git.

**Comment by rosenfeld** [comment]
Could you please explain it better? The permission denied problem is not due to git fetch most probably:

https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L59

There are other tasks that will affect the ownership of some files though through this recipe. That is why I manually chown -R \* here to simplify things (I know it is not the proper way of doing it, but it was easier this way - feel free to submit a pull request with the proper implementation if you want):

https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L132
https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L156

**Comment by planestraveler** [comment]
I'll try to see what i can do, during the install process I've already done the chown -R on the /var/www/gitorious directory and it did fix most of the issue I had.

**Comment by rosenfeld** [comment]
I guess it would require you no extra step if you had tried the recipe in a fresh environment with your http proxy env settings set up correctly from the beginning. Otherwise this recipe hasn't been planned for dealing well with script blocks that partially succeed. For instance, take a look at this script block:

https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L132

This script is not run if the database already exists:

`not_if "mysql -e 'show databases' | grep -q #{db_database}"`

but the database is created here:

https://github.com/rosenfeld/gitorious-cookbooks/blob/master/gitorious/recipes/default.rb#L127

So if any other command in that script block fails it is likely that your install script isn't going to work. For this particular case I believe that "bundle" has failed in this script because the proxy wasn't set up correctly. Then the "chown" command wasn't executed.

This is what I was referring to as not the proper way of creating this recipe, but it was much faster to design it this way and I was in a bit of hurry :P. Now I'm just lazy enough to fix this :)
